#!/bin/bash

# Push all environment variables from .env.local to Vercel
# Usage: ./scripts/push-env-to-vercel.sh

set -e

ENV_FILE=".env.local"

if [ ! -f "$ENV_FILE" ]; then
  echo "❌ Error: $ENV_FILE not found"
  exit 1
fi

echo "🚀 Pushing environment variables to Vercel..."
echo ""

# Skip these auto-generated variables
SKIP_VARS=("VERCEL_OIDC_TOKEN")

# Read and process each line
while IFS='=' read -r key value; do
  # Skip comments and empty lines
  [[ "$key" =~ ^#.*$ ]] && continue
  [[ -z "$key" ]] && continue

  # Skip variables in the skip list
  skip=false
  for skip_var in "${SKIP_VARS[@]}"; do
    if [ "$key" = "$skip_var" ]; then
      echo "⏭️  Skipping $key (auto-generated by Vercel)"
      skip=true
      break
    fi
  done

  if [ "$skip" = true ]; then
    continue
  fi

  # Remove quotes from value if present
  value="${value%\"}"
  value="${value#\"}"

  echo "📤 Adding $key to Vercel..."

  # Check if variable already exists
  existing=$(vercel env ls 2>/dev/null | grep "^$key " || echo "")

  if [ -n "$existing" ]; then
    echo "   ⚠️  $key already exists, removing old values..."
    # Remove existing values for all environments
    vercel env rm "$key" production --yes 2>/dev/null || true
    vercel env rm "$key" preview --yes 2>/dev/null || true
    vercel env rm "$key" development --yes 2>/dev/null || true
  fi

  # Add to each environment separately
  echo "$value" | vercel env add "$key" production
  echo "$value" | vercel env add "$key" preview
  echo "$value" | vercel env add "$key" development

  echo "   ✅ $key added to all environments"
  echo ""
done < <(grep -E "^[A-Z_]+=" "$ENV_FILE")

echo "✅ All environment variables pushed to Vercel!"
echo ""
echo "To verify, run: vercel env ls"
