import { NextRequest, NextResponse } from 'next/server'
import { stackServerApp } from '@/stack'
import { prisma } from '@/lib/prisma'
import JSZip from 'jszip'

// GET /api/projects/[id]/documents/export - Export all documents as ZIP
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const user = await stackServerApp.getUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { id: projectId } = await params

    // Verify user owns the project
    const project = await prisma.project.findUnique({
      where: { id: projectId }
    })

    if (!project || project.userId !== user.id) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 })
    }

    // Fetch all documents for the project
    const documents = await prisma.projectDocument.findMany({
      where: { projectId },
      orderBy: [
        { isBookmarked: 'desc' },
        { createdAt: 'desc' }
      ]
    })

    if (documents.length === 0) {
      return NextResponse.json({ error: 'No documents to export' }, { status: 404 })
    }

    // Create ZIP file
    const zip = new JSZip()

    // Group documents by type
    const docsByType: Record<string, typeof documents> = {}
    documents.forEach(doc => {
      if (!docsByType[doc.type]) {
        docsByType[doc.type] = []
      }
      docsByType[doc.type].push(doc)
    })

    // Add documents to ZIP organized by type
    for (const [type, docs] of Object.entries(docsByType)) {
      const folderName = type.toLowerCase().replace('_', '-')
      const folder = zip.folder(folderName)

      if (!folder) continue

      docs.forEach((doc, index) => {
        const extension = getFileExtension(doc.type)
        // Sanitize filename
        const sanitizedTitle = doc.title
          .replace(/[^a-z0-9_\-\s]/gi, '')
          .replace(/\s+/g, '-')
          .substring(0, 50)
        const filename = `${index + 1}-${sanitizedTitle}${extension}`

        folder.file(filename, doc.content)
      })
    }

    // Add a README with project info
    const readme = `# ${project.title || 'Project'} - Document Export

Exported: ${new Date().toISOString()}

## Project Information
- **Title**: ${project.title || 'Untitled'}
- **Description**: ${project.description || 'No description'}
- **Status**: ${project.status}
- **Created**: ${project.createdAt.toISOString()}
- **Total Documents**: ${documents.length}

## Documents by Type
${Object.entries(docsByType).map(([type, docs]) => `- **${type}**: ${docs.length} document(s)`).join('\n')}

## Bookmarked Documents
${documents.filter(d => d.isBookmarked).length} of ${documents.length} documents are bookmarked

---
Generated by VibePHX Project Builder
`

    zip.file('README.md', readme)

    // Generate ZIP buffer
    const zipBuffer = await zip.generateAsync({
      type: 'nodebuffer',
      compression: 'DEFLATE',
      compressionOptions: { level: 9 }
    })

    // Return ZIP file
    const projectName = (project.title || 'project')
      .replace(/[^a-z0-9_\-\s]/gi, '')
      .replace(/\s+/g, '-')
      .toLowerCase()
    const filename = `${projectName}-documents-${Date.now()}.zip`

    return new NextResponse(new Uint8Array(zipBuffer), {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': zipBuffer.length.toString()
      }
    })
  } catch (error) {
    console.error('Error exporting documents:', error)
    return NextResponse.json(
      { error: 'Failed to export documents' },
      { status: 500 }
    )
  }
}

function getFileExtension(type: string): string {
  switch (type) {
    case 'CODE':
      return '.ts'
    case 'PRD':
    case 'SPEC':
    case 'GUIDE':
    case 'BUILD_DOC':
    case 'MARKDOWN':
    case 'ARTIFACT':
      return '.md'
    case 'TEXT':
      return '.txt'
    default:
      return '.txt'
  }
}
